version: 2

jobs:
  lint:
    docker:
      - image: rust:1.36.0-buster
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            rustup component add rustfmt
            rustup component add clippy
      - run:
          name: cargo fmt
          command: |
            cargo fmt -- --check
      - run:
          name: cargo clippy
          command: |
            cargo clippy || true


workflows:
  version: 2
  build:
    jobs:
      - lint
